### ISSUE TITLE
How to make multiple derivations

### ISSUE THREAD

**Issue by Doosty** [mrcjkb/kickstart-nix.nvim#5]
Hello again, i am trying to define multiple nvim derivations so i can import them as needed. This is what ive tried, however the nvim-csharp is not available. Help much appreciated, thanks.
neovim-overlay.nix
``` nix
{inputs}: final: prev:
with final.pkgs.lib; let
  # ...
  packages-csharp = with pkgs; [
    omnisharp-roslyn # csharp lsp
    netcoredbg # csharp debug adapter
  ];
  plugins-csharp = with pkgs.vimPlugins; [
    (mkNvimPlugin inputs.omnisharp-vim "omnisharp.vim")
  ];
in {
  nvim-pkg = mkNeovim {
    plugins = all-plugins;
    inherit extraPackages;
  };
  nvim-csharp = mkNeovim {
    plugins = all-plugins ++ plugins-csharp;
    inherit extraPackages;
    inherit packages-csharp;
    appName = "nvim-csharp";
    viAlias = false;
    vimAlias = false;
  };
}
```

flake.nix
``` nix
# ...
in {
      packages = rec {
        default = nvim;
        nvim = pkgs.nvim-pkg;
        nvim-csharp = pkgs.nvim-csharp;
      };
      devShells = {
        default = shell;
      };
# ...
```

my nix configuration
``` nix
environment.systemPackages = with pkgs; [
    nvim-pkg
    nvim-csharp
  ];
```

**Comment by mrcjkb** [comment]
Hey 👋 

At the moment, `appName` only sets `NVIM_APPNAME` for the wrapper script, but it doesn't set the binary name.
I'll have to make a change to the `mkNeovim` function for that.

In the meantime, you can wrap `nvim-csharp/bin/nvim` as a workaround.

**Comment by Doosty** [comment]
I aliased nvim-csharp to this derivation config, and looking at the symlinks the nvim-csharp is in its own nix store directory, however the plugins and packages are not available from within that nvim, am i including the plugins and packages the right way?

```nix
let
  packages-csharp = with pkgs; [
    omnisharp-roslyn # csharp lsp
    netcoredbg # csharp debug adapter
  ];
  plugins-csharp = with pkgs.vimPlugins; [
    (mkNvimPlugin inputs.omnisharp-vim "omnisharp.vim")
  ];
in {
  nvim-csharp = mkNeovim {
    viAlias = false;
    vimAlias = false;
    appName = "nvim-csharp";
    plugins = plugins-all ++ plugins-csharp;
    extraPackages = packages-all ++ packages-csharp;
  };
}
```

```nix
  environment.shellAliases = {
      nvim-csharp = "${pkgs.nvim-csharp}/bin/nvim";
    };
  };
```

**Comment by mrcjkb** [comment]
:thinking: it looks fine to me. I just copied your derivation, was able to build it, and the `omnisharp-vim` plugin is loaded:

![omnisharp](https://github.com/mrcjkb/kickstart-nix.nvim/assets/12857160/cb0471d9-cc5f-47b4-bead-2bc27d94e146)

I can also run the `OmniSharp` executable from within Neovim:

![omnisharp](https://github.com/mrcjkb/kickstart-nix.nvim/assets/12857160/6e52c722-9310-4cd2-9f23-fe91cba3dad0)

**Comment by Doosty** [comment]
My alias was pointing to a previous build where there were no plugins, i had to relogin to the shell. Sorry, im a dummy, thanks for taking the time to test.
