### ISSUE TITLE
How to lazy load?

### ISSUE THREAD

**Issue by haru02w** [mrcjkb/kickstart-nix.nvim#6]
I ported my lazy.nvim config to this template and I'm having performance issues. Is there any way to lazy load plugins using this template or should I add [lazy-nix-helper.nvim](https://github.com/b-src/lazy-nix-helper.nvim) as a plugin and go from there?

**Comment by mrcjkb** [comment]
Hey 👋 

I'm afraid I don't have any experience with lazy-nix-helper.

Neovim has built-in support for lazy loading plugins with the [`:packadd[!]`](https://neovim.io/doc/user/repeat.html#%3Apackadd) command.

You can track down which plugins are causing startup performance issues (`nvim  --startuptime {fname}`) and set them to optional in the plugins list in `nix/neovim-overlay.nix`.

For example, `telescope-nvim` would become

```nix
{
  plugin = telescope-nvim;
  optional = true;
}
```

Then it won't be loaded until you call `:packadd! telescope.nvim` (or from lua, `vim.cmd { 'packadd!', 'telescope.nvim' }`).

If you want something more like the way lazy.nvim does it, I guess lazy-nix-helper is the way to go.

**Comment by haru02w** [comment]
Exactly what I was looking for. Thanks!
