### ISSUE TITLE
after folder won't load

### ISSUE THREAD

**Issue by haru02w** [mrcjkb/kickstart-nix.nvim#7]
How to reproduce:
```sh
git clone https://github.com/mrcjkb/kickstart-nix.nvim
cd kickstart-nix
echo "error('Should show this error at neovim startup')" > nvim/after/init.lua
git add -A
nix run .
```

**Comment by mrcjkb** [comment]
Hey 👋 

Try this:

```sh
mkdir -p nvim/after/plugin 
echo "error('Should show this error at neovim startup')" > nvim/after/plugin/init.lua
```

**Comment by haru02w** [comment]
not throwing the error yet. 
![image](https://github.com/mrcjkb/kickstart-nix.nvim/assets/74968611/45d8da8b-890a-45af-ae3b-854d4d0d4087)
![image](https://github.com/mrcjkb/kickstart-nix.nvim/assets/74968611/f3bae621-4ff3-4427-906c-e3721057acbd)

**Comment by mrcjkb** [comment]
Fixed with https://github.com/mrcjkb/kickstart-nix.nvim/commit/d0be2e86b42abffd500f282265fce018cc85049f.

Thanks for reporting :smile: 

On a side note: Your screenshot says you have the file in after/init.lua. It has to be in after/plugin/init.lua.

**Comment by haru02w** [comment]
Thanks for the quick fix. I didn't notice it was that simple

**Comment by mrcjkb** [comment]
> Thanks for the quick fix. I didn't notice it was that simple

Yeah, a dumb mistake on my end. I created the directory, then copied the directory into the directory, which resulted in `$out/after/after` instead of `$out/after/` :facepalm:
