### ISSUE TITLE
which-key plugin

### ISSUE THREAD

**Issue by dorekhov1** [mrcjkb/kickstart-nix.nvim#9]
Hi, thanks for this work, it has been very helpful to get started with my neovim setup on nixos. This is probably the best approach I've seen to handle neovim configurations on nixos!

I have configured the [which-key](https://github.com/folke/which-key.nvim) plugin with the simple `require('which-key').setup()` (after installing it with nix), and it works perfectly fine except for registers. When I press `"` nothing happens.  The plugin works fine outside the kickstart-nix setup, so I am wondering if there might be any configs that would prevent the plugin from working properly with registers. 

P.S. I think in general it would be a good idea to add this plugin to the setup to help people a) figure out what the default binding are, b) set and memorize new bindings

**Comment by dorekhov1** [comment]
Ah, that's right, I also do have tmux.nvim conflicting with it and I did not check the `:map "` 😅
Thanks for pointing it out!

As for the 
> I ended up deciding that it (and wf.nvim) are a bit too opinionated for a kickstarter setup.

I feel like with a kickstarter setup you are forced to decide on some keymaps, which has to be a bit opinionated already, so having a tool to help identify/navigate your keymaps would be very helpful (especially for someone who is fairly new to neovim, like myself).

**Comment by mrcjkb** [comment]
Ah, what a coincidence :smile: 

> I feel like with a kickstarter setup you are forced to decide on some keymaps, which has to be a bit opinionated already, so having a tool to help identify/navigate your keymaps would be very helpful (especially for someone who is fairly new to neovim, like myself).

That's a fair point. I guess I can re-add it.
